.TH "lxi_send" "3" "October 2017"

.SH "NAME"
lxi_send \- send message to LXI device

.SH "SYNOPSIS"
.PP
.B #include <lxi.h>

.B int lxi_send(int device, char *message, int length, int timeout);

.SH "DESCRIPTION"
.PP
The
.BR lxi_send()
function sends
.I length
bytes from the message buffer pointed to by
.I message

.PP
The 
.I timeout
is in miliseconds.

.SH "RETURN VALUE"

Upon successful completion 
.BR lxi_send() 
returns the number of bytes successfully sent, or
.BR LXI_ERROR
if an error occurred.

.SH "SEE ALSO"
.BR lxi_open (3),
.BR lxi_receive (3),
.BR lxi_disconnect (3),
