.TH "lxi_get_device_info" "3" "28 March 2016"

.SH "NAME"
lxi_get_device_info \- get LXI device information

.SH "SYNOPSIS"
.PP
.B #include <lxi.h>

.B int lxi_get_device_info(lxi_devices_t *devices, lxi_device_t *device);

.SH "DESCRIPTION"
.PP
The
.BR lxi_get_device_info()
function is an iterator function which can be used to iterate through the list of devices returned by 
.BR lxi_discover_devices()

.SH "RETURN VALUE"

Upon successful completion 
.BR lxi_get_device_info() 
returns
.BR LXI_OK
, or
.BR LXI_ERROR
if list is empty or end of list is reached.

.SH EXAMPLE
See
.BR lxi_discover_devices()

.SH "SEE ALSO"
.BR lxi_discover_devices (3)
.BR lxi_init (3)
.BR lxi_open (3),
.BR lxi_close (3)
.BR lxi_receive (3),
.BR lxi_disconnect (3),
